[package]
name = "server"
version = "1.0.0"
publish = false
edition.workspace = true

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
openssl = "0.10"
tokio = { version = "1", features = ["full"] }
