[package]
name = "server"
version = "1.0.0"
workspace = "../"
edition = "2018"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
futures = "0.3"
openssl = "0.10"
tokio = { version = "1.16.1", features = ["full"] }
