[package]
name = "databases"
version = "1.0.0"
publish = false
edition.workspace = true

[dependencies]
actix-web = "4"
diesel = { version = "2", features = ["sqlite", "r2d2"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
