name: Check examples

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  check-examples:
    name: Check examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1.3.5

      - name: Test examples
        env:
          RUSTFLAGS: -A dead-code -A unused-variables
        run: |
          cd examples
          cargo test
